#!/usr/bin/env python3

import os
from subprocess import call

repo_name = os.environ.get("GIT_REPO_NAME")
call(['python', '-m', 'pip', 'install', f'{repo_name}{os.path.sep}'])

celery_queue=os.environ.get("CELERY_QUEUE","celery")
log_level=os.environ.get("LOG_LEVEL","INFO")

call(["celery", "worker", "-n", celery_queue, "-Q", celery_queue, "-l", log_level])
